name: python

on: 
  push:
    branches: [main]
    
jobs:
  spell_check:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Spell Check
      uses: rojopolis/spellcheck-github-actions@0.45.0
      with:                                        
        output_file: spellcheck-output.txt